from datetime import UTC, datetime


MOCK_CFO_SUMMARY = {
    "generated_at": datetime.now(UTC).isoformat(),
    "mode": "mock",
    "cash_position": {"amount": 4_250_000, "currency": "USD"},
    "open_receivables": {"amount": 1_175_000, "currency": "USD"},
    "monthly_revenue": {"amount": 2_980_000, "currency": "USD"},
    "kpis": [
        {
            "label": "Cash runway",
            "value": "14.2 months",
            "trend": "up",
            "narrative": "Mock operating cash trend improved against the prior period.",
        },
        {
            "label": "DSO",
            "value": 42,
            "trend": "down",
            "narrative": "Mock receivables collection velocity improved by 3 days.",
        },
        {
            "label": "Gross margin",
            "value": "61.4%",
            "trend": "flat",
            "narrative": "Mock margin stayed within the expected operating band.",
        },
    ],
}

MOCK_TEMPLATE_ROWS: dict[str, list[dict[str, str | float]]] = {
    "cash_position_summary": [
        {"account": "Operating Cash", "balance": 2_850_000, "currency": "USD"},
        {"account": "Money Market", "balance": 1_400_000, "currency": "USD"},
    ],
    "ar_aging_summary": [
        {"bucket": "Current", "amount": 720_000, "currency": "USD"},
        {"bucket": "1-30", "amount": 310_000, "currency": "USD"},
        {"bucket": "31-60", "amount": 110_000, "currency": "USD"},
        {"bucket": "60+", "amount": 35_000, "currency": "USD"},
    ],
    "monthly_revenue_trend": [
        {"period": "2026-01", "revenue": 2_620_000, "currency": "USD"},
        {"period": "2026-02", "revenue": 2_740_000, "currency": "USD"},
        {"period": "2026-03", "revenue": 2_910_000, "currency": "USD"},
        {"period": "2026-04", "revenue": 2_980_000, "currency": "USD"},
    ],
    "pl_vs_budget": [
        {
            "period": "2026-Q1",
            "subsidiary_id": "NA",
            "line": "Revenue",
            "actual": 8_270_000,
            "budget": 7_950_000,
            "variance": 320_000,
            "variance_pct": 4.03,
            "currency": "USD",
        },
        {
            "period": "2026-Q1",
            "subsidiary_id": "NA",
            "line": "Cost of revenue",
            "actual": 3_180_000,
            "budget": 3_250_000,
            "variance": 70_000,
            "variance_pct": 2.15,
            "currency": "USD",
        },
        {
            "period": "2026-Q1",
            "subsidiary_id": "EMEA",
            "line": "Revenue",
            "actual": 4_430_000,
            "budget": 4_500_000,
            "variance": -70_000,
            "variance_pct": -1.56,
            "currency": "USD",
        },
    ],
    "yoy_comparison": [
        {
            "current_year": 2026,
            "prior_year": 2025,
            "subsidiary_id": "NA",
            "metric": "Revenue",
            "current_value": 8_270_000,
            "prior_value": 7_610_000,
            "change": 660_000,
            "change_pct": 8.67,
            "currency": "USD",
        },
        {
            "current_year": 2026,
            "prior_year": 2025,
            "subsidiary_id": "NA",
            "metric": "Gross margin",
            "current_value": 5_090_000,
            "prior_value": 4_630_000,
            "change": 460_000,
            "change_pct": 9.94,
            "currency": "USD",
        },
        {
            "current_year": 2026,
            "prior_year": 2025,
            "subsidiary_id": "EMEA",
            "metric": "Revenue",
            "current_value": 4_430_000,
            "prior_value": 4_210_000,
            "change": 220_000,
            "change_pct": 5.23,
            "currency": "USD",
        },
    ],
    "subsidiary_drilldown": [
        {
            "period": "2026-Q1",
            "subsidiary_id": "NA",
            "subsidiary_name": "North America",
            "department": "Enterprise Services",
            "revenue": 4_950_000,
            "expenses": 2_020_000,
            "operating_income": 2_930_000,
            "currency": "USD",
        },
        {
            "period": "2026-Q1",
            "subsidiary_id": "NA",
            "subsidiary_name": "North America",
            "department": "Customer Success",
            "revenue": 3_320_000,
            "expenses": 1_160_000,
            "operating_income": 2_160_000,
            "currency": "USD",
        },
        {
            "period": "2026-Q1",
            "subsidiary_id": "EMEA",
            "subsidiary_name": "EMEA",
            "department": "Enterprise Services",
            "revenue": 4_430_000,
            "expenses": 1_820_000,
            "operating_income": 2_610_000,
            "currency": "USD",
        },
    ],
    "running_projects": [
        {
            "project_id": "PRJ-1001",
            "project_name": "Revenue Automation Rollout",
            "customer": "Aster Manufacturing",
            "account_manager": "Maya Rao",
            "subsidiary_id": "NA",
            "status": "on_track",
            "budget": 420_000,
            "actual_cost": 231_000,
            "forecast_cost": 398_000,
            "currency": "USD",
        },
        {
            "project_id": "PRJ-1002",
            "project_name": "Multi-Book Close Optimization",
            "customer": "Northstar Retail",
            "account_manager": "Ethan Chen",
            "subsidiary_id": "NA",
            "status": "at_risk",
            "budget": 360_000,
            "actual_cost": 292_000,
            "forecast_cost": 388_000,
            "currency": "USD",
        },
        {
            "project_id": "PRJ-2001",
            "project_name": "EMEA RevRec Controls",
            "customer": "Helio Foods",
            "account_manager": "Maya Rao",
            "subsidiary_id": "EMEA",
            "status": "on_track",
            "budget": 280_000,
            "actual_cost": 141_000,
            "forecast_cost": 265_000,
            "currency": "USD",
        },
    ],
    "overdue_projects_by_account_manager": [
        {
            "account_manager": "Maya Rao",
            "overdue_project_count": 2,
            "total_overdue_amount": 145_000,
            "max_days_overdue": 31,
            "currency": "USD",
        },
        {
            "account_manager": "Ethan Chen",
            "overdue_project_count": 1,
            "total_overdue_amount": 82_000,
            "max_days_overdue": 18,
            "currency": "USD",
        },
    ],
}
