"""Webhook delivery tracking service — Release 12.0.

Manages the full lifecycle of an inbound webhook delivery:
  received → processing → succeeded | failed (→ retry) → dead_letter

Thread-safe; all writes go through the SQLAlchemy session in SessionLocal.
"""
from __future__ import annotations

import logging
import uuid

from app.core.database import SessionLocal
from app.models.webhooks import WebhookDelivery, WebhookDeliveryStats
from app.repositories.webhook_delivery_repository import WebhookDeliveryRepository

logger = logging.getLogger(__name__)


class WebhookDeliveryService:
    # ------------------------------------------------------------------
    # Create / record
    # ------------------------------------------------------------------

    def record_received(
        self,
        flow_id: str,
        payload_hash: str,
        request_id: str,
        tenant_id: int | None = None,
        max_attempts: int = 3,
        delivery_id: str | None = None,
    ) -> str:
        """Create a delivery record and return the *delivery_id*.

        If *delivery_id* is supplied (pre-generated by the caller) it is used;
        otherwise a new UUID hex is generated.
        """
        delivery_id = delivery_id or uuid.uuid4().hex
        with SessionLocal() as session:
            WebhookDeliveryRepository(session, tenant_id).create(
                delivery_id=delivery_id,
                flow_id=flow_id,
                payload_hash=payload_hash,
                request_id=request_id,
                tenant_id=tenant_id,
                max_attempts=max_attempts,
            )
        logger.info(
            "Webhook delivery recorded delivery_id=%s flow_id=%s request_id=%s",
            delivery_id,
            flow_id,
            request_id,
        )
        return delivery_id

    # ------------------------------------------------------------------
    # Status updates (called from Celery task)
    # ------------------------------------------------------------------

    def mark_succeeded(self, delivery_id: str) -> None:
        with SessionLocal() as session:
            WebhookDeliveryRepository(session).mark_succeeded(delivery_id)
        logger.info("Webhook delivery succeeded delivery_id=%s", delivery_id)

    def mark_failed(
        self,
        delivery_id: str,
        error: str,
        increment_attempt: bool = True,
        next_retry_at: str | None = None,
    ) -> None:
        with SessionLocal() as session:
            WebhookDeliveryRepository(session).mark_failed(
                delivery_id,
                error,
                increment_attempt=increment_attempt,
                next_retry_at=next_retry_at,
            )
        logger.warning(
            "Webhook delivery failed delivery_id=%s error=%s next_retry=%s",
            delivery_id,
            error[:120],
            next_retry_at,
        )

    def mark_dead_letter(self, delivery_id: str, error: str) -> None:
        with SessionLocal() as session:
            WebhookDeliveryRepository(session).mark_dead_letter(delivery_id, error)
        logger.error(
            "Webhook delivery dead-lettered delivery_id=%s error=%s",
            delivery_id,
            error[:120],
        )

    def mark_retrying(self, delivery_id: str, new_request_id: str) -> None:
        """Reset a failed/dead-letter delivery for manual re-queue."""
        with SessionLocal() as session:
            WebhookDeliveryRepository(session).mark_retrying(delivery_id, new_request_id)
        logger.info(
            "Webhook delivery reset for retry delivery_id=%s new_request_id=%s",
            delivery_id,
            new_request_id,
        )

    # ------------------------------------------------------------------
    # Reads
    # ------------------------------------------------------------------

    def get(self, delivery_id: str) -> WebhookDelivery | None:
        with SessionLocal() as session:
            return WebhookDeliveryRepository(session).get(delivery_id)

    def list_all(
        self,
        status: str | None = None,
        flow_id: str | None = None,
        limit: int = 100,
    ) -> list[WebhookDelivery]:
        with SessionLocal() as session:
            return WebhookDeliveryRepository(session).list_all(
                status=status, flow_id=flow_id, limit=limit
            )

    def list_for_flow(self, flow_id: str, limit: int = 50) -> list[WebhookDelivery]:
        with SessionLocal() as session:
            return WebhookDeliveryRepository(session).list_for_flow(flow_id, limit=limit)

    def stats(self) -> WebhookDeliveryStats:
        with SessionLocal() as session:
            return WebhookDeliveryRepository(session).stats()

    def dead_letter_count(self) -> int:
        with SessionLocal() as session:
            return WebhookDeliveryRepository(session).dead_letter_count()


webhook_delivery_service = WebhookDeliveryService()
